var contentData = JSON.stringify({
  work: `<h2>My Work</h2><p>I build modern websites and web applications using a variety of tools and techniques.</p><p>I'm available for new projects or updates / re-themeing of existing sites or apps. Click the "@ me" button to get in touch.</p><p>View my recent work:</p><ul><li><a href="https://trumpsupportersarent.com" target="_blank" rel="noopener noreferrer">Trump Supporters Aren't</a></li><li><a href="https://nurseteam.net" target="_blank" rel="noopener noreferrer">Nurse Team</a></li><li><a href="https://hubsandhops.com" target="_blank" rel="noopener noreferrer">Hubs and Hops</a></li><li><a href="https://hackthegates.org/" target="_blank" rel="noopener noreferrer">Hack the Gates</a></li><li><a href="https://wearefrac.org/" target="_blank" rel="noopener noreferrer">Florida Regional Admissions Counselors</a></li><li><a href="https://www.acceptgroup.org/" target="_blank" rel="noopener noreferrer">ACCEPT: Admissions Community Cultivating Equity and Peace Today</a></li><li><a href="https://github.com/ogdendavis/slack-freshdesk-tickets" target="_blank" rel="noopener noreferrer">Slack & Freshdesk Ticket App for Sachs Media Group</a></li></ul><p style="font-style:italic;font-size:0.75em;">Want additional client samples, or examples of the (award-winning) agency work I've done? Click the "@ me" button to get in touch.</p><p>Find out more about what I do:</p><ul><li><a href="https://github.com/ogdendavis" target="_blank" rel="noopener noreferrer">GitHub</a></li><li><a href="https://www.linkedin.com/in/lucasogdendavis" target="_blank" rel="noopener noreferrer">LinkedIn</a></li></ul>`,
  play: `<h2>Fun and Games</h2><p>When I'm not writing some sweet JavaScript or trouble-shooting a stubborn bit of CSS, I can often be found reading a novel (<a href="https://en.wikipedia.org/wiki/Terry_Pratchett" target="_blank" rel="noopener noreferrer">Terry Pratchett</a> is a favorite of mine), getting my sweat on (I used to own a gym!), or training my dogs.</p><p>If you're in Thomasville, you can often find me getting some socially-distanced takeout from some of our great downtown spots, like <a href="https://www.grassrootscoffee.com/" target="_blank" rel="noopener noreferrer">Grassroots</a>, <a href="https://hubsandhops.com/" target="_blank" rel="noopener noreferrer">Hubs and Hops</a>, and <a href="http://www.liamsthomasville.com/" target="_blank" rel="noopener noreferrer">Liam's</a>. If I'm not in my office or walking around downtown, I'm probably out of town on an adventure!</p>`,
  atme: `<h2>Get @ Me</h2><p>I live in Thomasville, Georgia, with my wife Kim, and our pets: Sylvie (cat), Figgy (dog), and Cedric (dog).</p><p>You can get in touch with me at:</p><div class="grid grid--email"></div><div class="grid grid--phone"></div>`,
  footer: {
    left: `<p>&#169; 2020, Lucas Ogden-Davis`,
    right: `<p>Looking for my brother, Joshua Ogden-Davis? He's <a href="https://www.ogden-davis.com/" target="_blank" rel="noopener noreferrer">here</a>.`,
  },
  header: `Having a great website is important, but living in a just and equitable society is even more important. I'm donating 10% of my revenue to <a href="https://www.blackgirlscode.com/" target="_blank" rel="noopener noreferrer">Black Girls Code</a>. I encourage you to speak up, <a href="https://www.vox.com/future-perfect/2020/6/9/21281538/how-to-donate-to-black-lives-matter-charity" target="_blank" rel="noopener noreferrer">donate</a> as you are able, and <a href="https://www.vote.org/" target="_blank" rel="noopener noreferrer">VOTE</a>.`,
});
