var contentData = JSON.stringify({
  "work": `<h2>My Work</h2><p>I build modern websites and web applications using a variety of tools and techniques.</p><p>I'm available for new projects or updates / re-themeing of existing sites or apps. Click the "@ me" button to get in touch.</p><p>View my recent client work:</p><ul><li><a href="https://hubsandhops.com" target="_blank">Hubs and Hops</a></li><li><a href="https://hackthegates.org/" target="_blank">Hack the Gates</a></li><li><a href="https://wearefrac.org/" target="_blank">Florida Regional Admissions Counselors</a></li><li><a href="https://www.acceptgroup.org/" target="_blank">ACCEPT: Admissions Community Cultivating Equity and Peace Today</a></li><li><a href="https://github.com/ogdendavis/slack-freshdesk-tickets" target="_blank">Slack & Freshdesk Ticket App for Sachs Media Group</a></li></ul><p style="font-style:italic;font-size:0.75em;">Want additional client examples, or samples of agency work I've done? Click the "@ me" button to get in touch.</p><p>Find out more about what I do:</p><ul><li><a href="https://github.com/ogdendavis" target="_blank">GitHub</a></li><li><a href="https://www.linkedin.com/in/lucasogdendavis" target="_blank">LinkedIn</a></li></ul>`,
  "play": `<h2>Fun and Games</h2><p>When I'm not writing some sweet JavaScript or trouble-shooting a stubborn bit of CSS, I can often be found getting my sweat on at <a href="http://thomasvillecrossfit.com/" target="_blank">Thomasville CrossFit</a>, reading a novel (<a href="https://en.wikipedia.org/wiki/Terry_Pratchett" target="_blank">Terry Pratchett</a> is a favorite of mine), or training my dogs.</p><p>If you're in Thomasville, you can often find me at some of our great downtown spots, like <a href="https://www.grassrootscoffee.com/" target="_blank">Grassroots</a>, <a href="https://hubsandhops.com/" target="_blank">Hubs and Hops</a>, and <a href="http://www.liamsthomasville.com/" target="_blank">Liam's</a>. If I'm not there, I'm probably out of town on an adventure.</p>`,
  "atme": `<h2>Get @ Me</h2><p>I live in Thomasville, Georgia, with my wife Kim, and our pets: Sylvie (cat), Figgy (dog), and Reg (dog).</p><p>You can get in touch with me at:</p><div class="grid grid--email"></div><div class="grid grid--phone"></div>`,
  "footer": {
    "left": `<p>&#169; 2020, Lucas Ogden-Davis`,
    "right": `<p>Looking for my brother, Joshua Ogden-Davis? He's <a href="https://www.ogden-davis.com/" target="_blank">here</a>.`
  }
});
